### ISSUE TITLE
Package Compiler version from Running Compiler

### ISSUE THREAD

**Issue by jmrtnz94** [alexcampana/ApiFirstMediatR#69]
I've ran into this issue a few times while using the ApiFirstMediatR.

I think anytime `Microsoft.CodeAnalysis.CSharp` is bumped a version we run into this issue.
Ref: https://github.com/alexcampana/ApiFirstMediatR/pull/64

```
'...ApiFirstMediatR.Generator.dll' references version '4.5.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'
```

**Comment by jmrtnz94** [comment]
This stacks answer explains it: https://stackoverflow.com/a/72670807/4585661

**Comment by alexcampana** [comment]
That makes sense, I'll roll it back to the earliest .NET 6 version since that's the lowest version we support
